version: '2'
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8081:80
      - 443:443
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
       - DRONE_SERVER_HOST=127.0.0.1
       - DRONE_SERVER_PROTO=https
       - DRONE_TLS_AUTOCERT=false
       - DRONE_RPC_SECRET=drone-secret
       - DRONE_AGENTS_ENABLED=true
       # GitHub Config
       - DRONE_GITHUB_SERVER=https://github.com
       - DRONE_GITHUB_CLIENT_ID=your_id
       - DRONE_GITHUB_CLIENT_SECRET=your_secret
       - DRONE_LOGS_PRETTY=true
       - DRONE_LOGS_COLOR=true
  drone-agent:
    image: drone/agent:1
    restart: always
    depends_on: 
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server
      - DRONE_RPC_SECRET=drone-secret
      - DRONE_RUNNER_CAPACITY=3